### PR TITLE
Replace staging roborio target with Hardknott

### PR DESCRIPTION
**Pull request by RyanHir**
NI is preparing to release a new version of their operating system based on Yocto Hardknott which will bring GCC 10.2. As Hardknott packages are not on the repo just yet, we will need to use the same infrastructure from staging when building the Hardknott toolchain.

### CODE REVIEW

**Comment by marshallmassengill** [comment]
Hey Ryan, you might want to take a look at these before you get too much further: 
https://github.com/ni/meta-nilrt/pull/300
https://github.com/ni/meta-nilrt/pull/307
https://github.com/ni/meta-nilrt/pull/310

It's possible there is some effort underway to support Hardknott for the arm systems but they've been removing the arm bits for a while based on observing the repo activity.  I think we're going to be stuck with Sumo for the long haul.

**Comment by RyanHir** [comment]
Thank you for the heads up,

As you are probably aware, the RoboRIO toolchains is mostly targeted for FRC competition. As the system image for FRC is still based on Sumo, I am still providing the Sumo toolchain. Plus I consider the Hardknott toolchain experimental as I am building more libraries than the other toolchains to make up for the lack of repos.

NI removing ARM support is concerning as bumping the GCC version is greatly anticipated for the RoboRIO.

**Comment by marshallmassengill** [comment]
No worries.  I've been watching this repo for a while and it's amazing work.  I am definitely eager to see it become the official build process.  I do doubt we are getting any updates for the toolchain on the RoboRIO though.  It seems like they have kept the arm systems on the old Sumo builds.  There was an issue or a PR or a forum post that was opened at one point that I can't find now... Someone at NI explained they are still messing around with arm but they aren't planning an updating things for it beyond Sumo.  It's definitely worth confirming with them.

**Comment by RyanHir** [comment]
I spoke to @PeterJohnson on the FRC Discord and he will bring up the topic of Hardknott for the RoboRIO to NI in a future meeting. If you can find a link to the post that NI is still working on ARM support, that would be great.

As for this project becoming an official piece of @wpilibsuite, I have heard that it will be considered for 2023 as this project stabilized too late into 2021 for it to be considered for 2022.

**Pull request merged**
